version: "3.9"

services:
  api:
    build: .
    container_name: payment_api
    ports:
      - "8000:8000"
      - "9000:9000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/payments
      REDIS_URL: redis://redis:6379/0
      RAFIKI_API_URL: http://localhost:3000
      RAFIKI_AUTH_TOKEN: dummy_token_for_now
      RAFIKI_WEBHOOK_SECRET: dummy_secret_for_now
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    container_name: payment_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments

     volumes:
       - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: payment_redis
    ports:
      - "6379:6379"

 volumes:
   postgres_data: